/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package houserentalmanagementsystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MICHAEL
 */
public class Admin_Dashboard extends javax.swing.JFrame {
     private JFrame frame;
    /**
     * Creates new form AdminDashboard
     */
    public Admin_Dashboard() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addusersbtn = new javax.swing.JButton();
        roomreportbtn = new javax.swing.JButton();
        addroomsbtn = new javax.swing.JButton();
        addemployeesbtn = new javax.swing.JButton();
        addservicebtn = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addtenantbtn = new javax.swing.JButton();
        helpbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jTextField22 = new javax.swing.JTextField();
        manageuserbtn = new javax.swing.JButton();
        jTextField23 = new javax.swing.JTextField();
        tenantreportbtn = new javax.swing.JButton();
        jTextField24 = new javax.swing.JTextField();
        manageserviceprovidersbtn = new javax.swing.JButton();
        managetenatsbtn = new javax.swing.JButton();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        addpaymentbtn = new javax.swing.JButton();
        addassetbtn = new javax.swing.JButton();
        jTextField28 = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        manageroomsbtn = new javax.swing.JButton();
        manageemployeesbtn = new javax.swing.JButton();
        managepaymentbtn = new javax.swing.JButton();
        manageassestsbtn = new javax.swing.JButton();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        rentreportbtn = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("WELCOME TO ADMIN DASHBOARD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 4, -1, -1));

        addusersbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        addusersbtn.setForeground(new java.awt.Color(0, 102, 255));
        addusersbtn.setText("Add Users ");
        addusersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addusersbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addusersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        roomreportbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        roomreportbtn.setForeground(new java.awt.Color(0, 204, 255));
        roomreportbtn.setText("Rooms");
        roomreportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomreportbtnActionPerformed(evt);
            }
        });
        jPanel1.add(roomreportbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        addroomsbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        addroomsbtn.setForeground(new java.awt.Color(0, 102, 255));
        addroomsbtn.setText("Add Rooms");
        addroomsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroomsbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addroomsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, -1));

        addemployeesbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        addemployeesbtn.setForeground(new java.awt.Color(51, 102, 255));
        addemployeesbtn.setText("Add Employees");
        addemployeesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addemployeesbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addemployeesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 170, -1));

        addservicebtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        addservicebtn.setForeground(new java.awt.Color(0, 102, 204));
        addservicebtn.setText("Add Service Providers");
        addservicebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addservicebtnActionPerformed(evt);
            }
        });
        jPanel1.add(addservicebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(255, 255, 255));
        jTextField14.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(204, 102, 0));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText(">");
        jTextField14.setBorder(null);
        jTextField14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, 30));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(255, 255, 255));
        jTextField15.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(204, 102, 0));
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText(">");
        jTextField15.setBorder(null);
        jTextField15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 30));

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(255, 255, 255));
        jTextField16.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(204, 102, 0));
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText(">");
        jTextField16.setBorder(null);
        jTextField16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, -1, 30));

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(255, 255, 255));
        jTextField18.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(204, 102, 0));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText(">");
        jTextField18.setBorder(null);
        jTextField18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, 30));

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(255, 255, 255));
        jTextField19.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(204, 102, 0));
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText(">");
        jTextField19.setBorder(null);
        jTextField19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 30));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("CLICK ACTIVITY YOU WANT TO PERFORM ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 46, -1, -1));

        addtenantbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        addtenantbtn.setForeground(new java.awt.Color(51, 102, 255));
        addtenantbtn.setText("Add Tenants");
        addtenantbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtenantbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addtenantbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 190, -1));

        helpbtn.setBackground(new java.awt.Color(255, 255, 255));
        helpbtn.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        helpbtn.setForeground(new java.awt.Color(153, 255, 102));
        helpbtn.setText("Help");
        helpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(helpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        logoutbtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutbtn.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 0, 51));
        logoutbtn.setText("LOG OUT");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(255, 255, 255));
        jTextField22.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField22.setForeground(new java.awt.Color(204, 102, 0));
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText(">");
        jTextField22.setBorder(null);
        jTextField22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, 30));

        manageuserbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        manageuserbtn.setText("Manage Users");
        manageuserbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageuserbtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageuserbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jTextField23.setEditable(false);
        jTextField23.setBackground(new java.awt.Color(255, 255, 255));
        jTextField23.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField23.setForeground(new java.awt.Color(204, 102, 0));
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setText(">");
        jTextField23.setBorder(null);
        jTextField23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, 30));

        tenantreportbtn.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        tenantreportbtn.setForeground(new java.awt.Color(0, 204, 255));
        tenantreportbtn.setText("Tenants");
        tenantreportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantreportbtnActionPerformed(evt);
            }
        });
        jPanel1.add(tenantreportbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, -1, -1));

        jTextField24.setEditable(false);
        jTextField24.setBackground(new java.awt.Color(255, 255, 255));
        jTextField24.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField24.setForeground(new java.awt.Color(204, 102, 0));
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText(">");
        jTextField24.setBorder(null);
        jTextField24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, 30));

        manageserviceprovidersbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        manageserviceprovidersbtn.setText("Manage Service Providers");
        manageserviceprovidersbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageserviceprovidersbtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageserviceprovidersbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        managetenatsbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        managetenatsbtn.setForeground(new java.awt.Color(51, 51, 51));
        managetenatsbtn.setText("Manage Tenants");
        managetenatsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managetenatsbtnActionPerformed(evt);
            }
        });
        jPanel1.add(managetenatsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jTextField25.setEditable(false);
        jTextField25.setBackground(new java.awt.Color(255, 255, 255));
        jTextField25.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField25.setForeground(new java.awt.Color(204, 102, 0));
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setText(">");
        jTextField25.setBorder(null);
        jTextField25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, 30));

        jTextField26.setEditable(false);
        jTextField26.setBackground(new java.awt.Color(255, 255, 255));
        jTextField26.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField26.setForeground(new java.awt.Color(204, 102, 0));
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setText(">");
        jTextField26.setBorder(null);
        jTextField26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, 30));

        jLabel3.setBackground(new java.awt.Color(0, 51, 255));
        jLabel3.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 255));
        jLabel3.setText("choose Recording Activites");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, 30));

        jLabel4.setBackground(new java.awt.Color(0, 51, 255));
        jLabel4.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel4.setText("Choose Manage Activity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 81, -1, 30));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Engravers MT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));
        jLabel5.setText("Choose Report To Generate");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 260, 30));

        jTextField27.setEditable(false);
        jTextField27.setBackground(new java.awt.Color(255, 255, 255));
        jTextField27.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField27.setForeground(new java.awt.Color(204, 102, 0));
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setText(">");
        jTextField27.setBorder(null);
        jTextField27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, 30));

        addpaymentbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        addpaymentbtn.setForeground(new java.awt.Color(0, 102, 204));
        addpaymentbtn.setText("Add Payment");
        addpaymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpaymentbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addpaymentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        addassetbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        addassetbtn.setForeground(new java.awt.Color(0, 102, 204));
        addassetbtn.setText("Add Rental Assets");
        addassetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addassetbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addassetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, -1));

        jTextField28.setEditable(false);
        jTextField28.setBackground(new java.awt.Color(255, 255, 255));
        jTextField28.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField28.setForeground(new java.awt.Color(204, 102, 0));
        jTextField28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField28.setText(">");
        jTextField28.setBorder(null);
        jTextField28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, 30));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 10, 380));

        manageroomsbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        manageroomsbtn.setText("Manage Rooms");
        manageroomsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageroomsbtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageroomsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        manageemployeesbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        manageemployeesbtn.setText("Manage Employees");
        manageemployeesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageemployeesbtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageemployeesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 210, -1));

        managepaymentbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        managepaymentbtn.setText("Manage Payment");
        managepaymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managepaymentbtnActionPerformed(evt);
            }
        });
        jPanel1.add(managepaymentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        manageassestsbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        manageassestsbtn.setText("Manage Rental Properties");
        manageassestsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageassestsbtnActionPerformed(evt);
            }
        });
        jPanel1.add(manageassestsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 270, -1));

        jTextField29.setEditable(false);
        jTextField29.setBackground(new java.awt.Color(255, 255, 255));
        jTextField29.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField29.setForeground(new java.awt.Color(204, 102, 0));
        jTextField29.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField29.setText(">");
        jTextField29.setBorder(null);
        jTextField29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, 30));

        jTextField30.setEditable(false);
        jTextField30.setBackground(new java.awt.Color(255, 255, 255));
        jTextField30.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField30.setForeground(new java.awt.Color(204, 102, 0));
        jTextField30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField30.setText(">");
        jTextField30.setBorder(null);
        jTextField30.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, 30));

        jTextField31.setEditable(false);
        jTextField31.setBackground(new java.awt.Color(255, 255, 255));
        jTextField31.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField31.setForeground(new java.awt.Color(204, 102, 0));
        jTextField31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField31.setText(">");
        jTextField31.setBorder(null);
        jTextField31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, 30));

        jTextField32.setEditable(false);
        jTextField32.setBackground(new java.awt.Color(255, 255, 255));
        jTextField32.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField32.setForeground(new java.awt.Color(204, 102, 0));
        jTextField32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField32.setText(">");
        jTextField32.setBorder(null);
        jTextField32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, 30));

        jTextField33.setEditable(false);
        jTextField33.setBackground(new java.awt.Color(255, 255, 255));
        jTextField33.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField33.setForeground(new java.awt.Color(204, 102, 0));
        jTextField33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField33.setText(">");
        jTextField33.setBorder(null);
        jTextField33.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, 30));

        rentreportbtn.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        rentreportbtn.setForeground(new java.awt.Color(51, 204, 255));
        rentreportbtn.setText("Rent Payment");
        rentreportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentreportbtnActionPerformed(evt);
            }
        });
        jPanel1.add(rentreportbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, -1, -1));
        jPanel1.add(jProgressBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 10, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addusersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addusersbtnActionPerformed
             this.dispose();
             RegisterUsers ru = new RegisterUsers();
             ru.setVisible(true);
       
    }//GEN-LAST:event_addusersbtnActionPerformed

    private void addservicebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addservicebtnActionPerformed
        this.dispose();
        OtherServiceproviders osp = new OtherServiceproviders();
        osp.setVisible(true);
    }//GEN-LAST:event_addservicebtnActionPerformed

    private void addemployeesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addemployeesbtnActionPerformed
        this.dispose();
        RegisterRentalEmployees re = new RegisterRentalEmployees();
        re.setVisible(true);
      
    }//GEN-LAST:event_addemployeesbtnActionPerformed

    private void addroomsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroomsbtnActionPerformed
         this.dispose();
         RecordRooms rms = new RecordRooms();
         rms.setVisible(true);        
    }//GEN-LAST:event_addroomsbtnActionPerformed

    private void helpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpbtnActionPerformed
             this.dispose();
         Login log = new Login();
         log.setVisible(true);      
    }//GEN-LAST:event_helpbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
       
        this.dispose();
        Logout lg = new Logout();
        lg.setVisible(true);
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void roomreportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomreportbtnActionPerformed
       this.dispose();
      RoomsReport roomrepo = new RoomsReport();
      roomrepo.setVisible(true);
       
    }//GEN-LAST:event_roomreportbtnActionPerformed

    private void addtenantbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtenantbtnActionPerformed
        this.dispose();
        RegisterTenants rt = new RegisterTenants();
        rt.setVisible(true);
    }//GEN-LAST:event_addtenantbtnActionPerformed

    private void manageuserbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageuserbtnActionPerformed
       this.dispose();
       ManageUsers mu = new ManageUsers();
       mu.setVisible(true);
    }//GEN-LAST:event_manageuserbtnActionPerformed

    private void tenantreportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantreportbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenantreportbtnActionPerformed

    private void manageserviceprovidersbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageserviceprovidersbtnActionPerformed
        this.dispose();
        ManageServiceProviders service  = new ManageServiceProviders();
        service.setVisible(true);
    }//GEN-LAST:event_manageserviceprovidersbtnActionPerformed

    private void managetenatsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managetenatsbtnActionPerformed
          this.dispose();
          ManageTenants mt = new ManageTenants();
          mt.setVisible(true);         
    }//GEN-LAST:event_managetenatsbtnActionPerformed

    private void addpaymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpaymentbtnActionPerformed
        this.dispose();
        RentPayment rp = new RentPayment();
        rp.setVisible(true);
    }//GEN-LAST:event_addpaymentbtnActionPerformed

    private void addassetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addassetbtnActionPerformed
        this.dispose();
        RecordRentalProperties prop = new RecordRentalProperties();
        prop.setVisible(true);
    }//GEN-LAST:event_addassetbtnActionPerformed

    private void manageroomsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageroomsbtnActionPerformed
       this.dispose();
       ManageRooms mr = new ManageRooms();
       mr.setVisible(true);
    }//GEN-LAST:event_manageroomsbtnActionPerformed

    private void manageemployeesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageemployeesbtnActionPerformed
        this.dispose();
        ManageEmployees emp = new ManageEmployees();
        emp.setVisible(true);
    }//GEN-LAST:event_manageemployeesbtnActionPerformed

    private void managepaymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managepaymentbtnActionPerformed
        this.dispose();
        ManageRentPayment rent = new ManageRentPayment();
        rent.setVisible(true);
    }//GEN-LAST:event_managepaymentbtnActionPerformed

    private void manageassestsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageassestsbtnActionPerformed
        this.dispose();
        ManageRentalProperties prop = new ManageRentalProperties();
        prop.setVisible(true);
    }//GEN-LAST:event_manageassestsbtnActionPerformed

    private void rentreportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentreportbtnActionPerformed
        this.dispose();
        RentPaymentReport rentrepo = new RentPaymentReport();
        rentrepo.setVisible(true);
    }//GEN-LAST:event_rentreportbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addassetbtn;
    private javax.swing.JButton addemployeesbtn;
    private javax.swing.JButton addpaymentbtn;
    private javax.swing.JButton addroomsbtn;
    private javax.swing.JButton addservicebtn;
    private javax.swing.JButton addtenantbtn;
    private javax.swing.JButton addusersbtn;
    private javax.swing.JButton helpbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton manageassestsbtn;
    private javax.swing.JButton manageemployeesbtn;
    private javax.swing.JButton managepaymentbtn;
    private javax.swing.JButton manageroomsbtn;
    private javax.swing.JButton manageserviceprovidersbtn;
    private javax.swing.JButton managetenatsbtn;
    private javax.swing.JButton manageuserbtn;
    private javax.swing.JButton rentreportbtn;
    private javax.swing.JButton roomreportbtn;
    private javax.swing.JButton tenantreportbtn;
    // End of variables declaration//GEN-END:variables
}
