/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package houserentalmanagementsystem;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MICHAEL
 */
public class ManageUsers extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet rs;
    Connection con;
    private JFrame frame;
    DefaultTableModel model;

    /**
     * Creates new form DbUpdater
     */
    public ManageUsers() {
        initComponents();
        this.setResizable(false);
    }

    private void retrieveusers() {
        try {
            String sql = "SELECT user_id, username, PhoneNumber, password, role, SecurityQuestion, Answer FROM Users";
            con = DriverManager.getConnection("jdbc:mysql://localhost/rentalmanagementsystem", "root", "");
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) userstable.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                String id = rs.getString(1);
                String username = rs.getString(2);
                String phonenumber = rs.getString(3);
                String pass = rs.getString(4);
                String position = rs.getString(5);
                String quest = rs.getString(6);
                String answers = rs.getString(7);
                model.addRow(new String[]{id, username, phonenumber, pass, position, quest, answers});
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public Boolean updateusers(String id, String name, String phns, String passt, String usrole, String userquery, String ansquest) {
        String query = "UPDATE Users SET username='" + name + "',phonenumber='" + phns + "',password='" + passt + "', role ='" + usrole + "', SecurityQuestion='" + userquery + "',Answer='" + ansquest + "' WHERE user_id= '" + id + "'";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/rentalmanagementsystem", "root", "");
            ps = con.prepareStatement(query);
            ps.execute(query);
            return true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            return false;
        }
    }

    public Boolean deleteusers(String id) {

        String sql = "DELETE FROM Users WHERE user_id ='" + id + "'";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/rentalmanagementsystem", "root", "");
            ps = con.prepareStatement(sql);
            ps.execute(sql);
            return true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            return false;
        }
    }

    private void filterusers(String query) {
        DefaultTableModel model2 =  (DefaultTableModel) userstable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model2);
        userstable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userstable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        ansu = new javax.swing.JTextField();
        ptxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        retrievebtn = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        updbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        passtxt = new javax.swing.JTextField();
        roleu = new javax.swing.JTextField();
        secu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "MANAGE USERS ACCOUNTS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userstable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Id", "username", "Phonenumber", "Password", "role", "security Question", "Answer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(userstable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 90, 730, 300));

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel1.setText("Phonenumber:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel2.setText("Answer:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, -1, -1));

        usertxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        jPanel1.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 200, -1));

        ansu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(ansu, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 200, -1));

        ptxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ptxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptxtActionPerformed(evt);
            }
        });
        jPanel1.add(ptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 200, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 84, -1, -1));

        retrievebtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        retrievebtn.setForeground(new java.awt.Color(0, 102, 255));
        retrievebtn.setText("RETRIEVE");
        retrievebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrievebtnActionPerformed(evt);
            }
        });
        jPanel1.add(retrievebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        exitbutton.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        exitbutton.setForeground(new java.awt.Color(0, 204, 204));
        exitbutton.setText("EXIT");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(exitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 410, -1, -1));

        backbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(204, 51, 0));
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        delbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        delbtn.setText("DELETE");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });
        jPanel1.add(delbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        updbtn.setBackground(new java.awt.Color(255, 255, 255));
        updbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        updbtn.setForeground(new java.awt.Color(153, 0, 153));
        updbtn.setText("UPDATE");
        updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbtnActionPerformed(evt);
            }
        });
        jPanel1.add(updbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 3, 24)); // NOI18N
        jLabel5.setText("SEARCH");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 55, 110, -1));

        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 52, 228, -1));

        jLabel6.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel6.setText("Username:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel7.setText("Role:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        jLabel8.setText("Security Q:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        passtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 200, 200, -1));

        roleu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(roleu, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 260, 200, -1));

        secu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(secu, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
      
             this.dispose();

    }//GEN-LAST:event_backbtnActionPerformed

    private void userstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userstableMouseClicked
        String name = userstable.getValueAt(userstable.getSelectedRow(), 1).toString();
        String pno = userstable.getValueAt(userstable.getSelectedRow(), 2).toString();
        String pass = userstable.getValueAt(userstable.getSelectedRow(), 3).toString();
        String roles = userstable.getValueAt(userstable.getSelectedRow(), 4).toString();
        String security = userstable.getValueAt(userstable.getSelectedRow(), 5).toString();
        String asn = userstable.getValueAt(userstable.getSelectedRow(), 6).toString();

        ptxt.setText(name);
        usertxt.setText(pno);
        passtxt.setText(pass);
        roleu.setText(roles);
        secu.setText(security);
        ansu.setText(asn);
    }//GEN-LAST:event_userstableMouseClicked

    private void retrievebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrievebtnActionPerformed
     retrieveusers();
    }//GEN-LAST:event_retrievebtnActionPerformed

    private void updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbtnActionPerformed
        try {
            if (ptxt.getText().isEmpty() || usertxt.getText().isEmpty() || passtxt.getText().isEmpty()|| roleu.getText().isEmpty()|| secu.getText().isEmpty()|| ansu.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No row is selected..!!\nPlease select a row to update...");
            } else {
                int index = userstable.getSelectedRow();
                String id = userstable.getValueAt(index, 0).toString();  //index=rownumber and 0 represents first column..

                if (updateusers(id, ptxt.getText(), usertxt.getText(), passtxt.getText(), roleu.getText(), secu.getText(),ansu.getText())){
                    JOptionPane.showMessageDialog(null, "Data Updated Successfully");
                    ptxt.setText("");
                    usertxt.setText("");
                    passtxt.setText("");
                    roleu.setText("");
                    secu.setText("");
                    ansu.setText("");
                    retrieveusers();
                } else {
                    JOptionPane.showMessageDialog(null, "Data Not Updated ");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }  
    }//GEN-LAST:event_updbtnActionPerformed

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed

        try {
            String[] options = {"Yes", "No"};
            int answer = JOptionPane.showOptionDialog(null, " Are you Sure to delete ??", "Delete Options", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

            if (answer == 0) {
              String id = userstable.getValueAt(userstable.getSelectedRow(), 0).toString();
                if (deleteusers(id)) {
                    JOptionPane.showMessageDialog(null, "Data Deleted Successfully");
                    ptxt.setText("");
                    usertxt.setText("");
                    passtxt.setText("");
                    roleu.setText("");
                    secu.setText("");
                    ansu.setText("");
                    retrieveusers();
                } else {
                    JOptionPane.showMessageDialog(null, " Data Not Deleted ");
                }
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }  
    }//GEN-LAST:event_delbtnActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(null, "Confirm You Want to Exit", "Manage Users Accounts Module", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ptxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptxtActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String query1 = jTextField1.getText();
        filterusers(query1);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansu;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton delbtn;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField passtxt;
    private javax.swing.JTextField ptxt;
    private javax.swing.JButton retrievebtn;
    private javax.swing.JTextField roleu;
    private javax.swing.JTextField secu;
    private javax.swing.JButton updbtn;
    private javax.swing.JTable userstable;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
