/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package houserentalmanagementsystem;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MICHAEL
 */
public class ManageRentalProperties extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet rs;
    Connection con;
    private JFrame frame;
    DefaultTableModel model;

    /**
     * Creates new form DbUpdater
     */
    public ManageRentalProperties() {
        initComponents();
        this.setResizable(false);
    }

    private void retrieve() {
        try {
            String sql = "SELECT * FROM rental_properties";
            con = DriverManager.getConnection("jdbc:mysql://localhost/rentalmanagementsystem", "root", "");
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) property.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                String id = rs.getString(1);
                String name = rs.getString(2);
                String quantity = rs.getString(3);
                String price = rs.getString(4);
                model.addRow(new String[]{id, name, quantity, price});

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    public Boolean update(String id, String name, String quant, String prices) {
        String query = "UPDATE rental_properties SET name='" + name + "',quantity='" + quant + "',price='" + prices + "' WHERE property_id= '" + id + "'";

        try {

            con = DriverManager.getConnection("jdbc:mysql://localhost/rentalmanagementsystem", "root", "");
            ps = con.prepareStatement(query);

            ps.execute(query);

            return true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            return false;
        }
    }

    public Boolean delete(String id) {

        String sql = "DELETE FROM rental_properties WHERE property_id ='" + id + "'";

        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/rentalmanagementsystem", "root", "");

            ps = con.prepareStatement(sql);

            ps.execute(sql);
            return true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            return false;
        }

    }

    private void filter(String query) {
        DefaultTableModel model2 =  (DefaultTableModel) property.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model2);
        property.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        property = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtxt = new javax.swing.JTextField();
        ptxt = new javax.swing.JTextField();
        ntxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        retrievebutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        updatebutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "MANAGEMENT PROPERTY MANAGEMENT MODULE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Perpetua Titling MT", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        property.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        property.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property Id", "Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        property.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                propertyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(property);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 100, 650, 290));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel1.setText("Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel2.setText("Price:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        qtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(qtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 200, -1));

        ptxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(ptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, 200, -1));

        ntxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntxtActionPerformed(evt);
            }
        });
        jPanel1.add(ntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 200, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 84, -1, -1));

        retrievebutton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        retrievebutton.setForeground(new java.awt.Color(51, 0, 255));
        retrievebutton.setText("RETRIEVE");
        retrievebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retrievebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(retrievebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        exitbutton.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        exitbutton.setForeground(new java.awt.Color(0, 204, 204));
        exitbutton.setText("EXIT");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(exitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 450, -1, -1));

        backbutton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        backbutton.setForeground(new java.awt.Color(255, 51, 51));
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, -1));

        deletebutton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        deletebutton.setForeground(new java.awt.Color(51, 51, 51));
        deletebutton.setText("DELETE");
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        updatebutton.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        updatebutton.setForeground(new java.awt.Color(153, 0, 153));
        updatebutton.setText("UPDATE");
        updatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(updatebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel5.setText("SEARCH");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 55, 110, -1));

        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 52, 228, -1));

        jLabel6.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel6.setText("Quantity:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
          Admin_Dashboard ad = new Admin_Dashboard();
          ad.setVisible(true);
             this.dispose();

    }//GEN-LAST:event_backbuttonActionPerformed

    private void propertyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertyMouseClicked
      String name = property.getValueAt(property.getSelectedRow(), 1).toString();
        String pquant = property.getValueAt(property.getSelectedRow(), 2).toString();
        String pprice = property.getValueAt(property.getSelectedRow(), 3).toString();
     //   String cge = jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString();
        
        
        ntxt.setText(name);
        qtxt.setText(pquant);
        ptxt.setText(pprice);
        

    }//GEN-LAST:event_propertyMouseClicked

    private void retrievebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retrievebuttonActionPerformed

        retrieve();
    }//GEN-LAST:event_retrievebuttonActionPerformed

    private void updatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttonActionPerformed
        try {
            if (ntxt.getText().isEmpty() || qtxt.getText().isEmpty() || ptxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No row is selected..!!\nPlease select a row to update...");
            } else {
                int index = property.getSelectedRow();
                String id = property.getValueAt(index, 0).toString();  //index=rownumber and 0 represents first column..

                if (update(id, ntxt.getText(), qtxt.getText(), ptxt.getText())) {
                    JOptionPane.showMessageDialog(null, "Data Updated Successfully");
                    ntxt.setText("");
                    qtxt.setText("");
                    ptxt.setText("");
                    retrieve();

                } else {
                    JOptionPane.showMessageDialog(null, "Data Not Updated ");
                }

            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_updatebuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed

        try {

            String[] options = {"Yes", "No"};
            int answer = JOptionPane.showOptionDialog(null, " Are you Sure to delete ??", "Delete Options", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

            if (answer == 0) {

                String id = property.getValueAt(property.getSelectedRow(), 0).toString();

                if (delete(id)) {

                    JOptionPane.showMessageDialog(null, "Data Deleted Successfully");
                    ntxt.setText("");
                    qtxt.setText("");
                    ptxt.setText("");
                    retrieve();

                } else {
                    JOptionPane.showMessageDialog(null, " Data Not Deleted ");
                }
  
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    
    }//GEN-LAST:event_deletebuttonActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(null, "Confirm You Want to Exit", "Property Management Module", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ntxtActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String query1 = jTextField1.getText();
        filter(query1);
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRentalProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRentalProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRentalProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRentalProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRentalProperties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField ntxt;
    private javax.swing.JTable property;
    private javax.swing.JTextField ptxt;
    private javax.swing.JTextField qtxt;
    private javax.swing.JButton retrievebutton;
    private javax.swing.JButton updatebutton;
    // End of variables declaration//GEN-END:variables
}
