/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package houserentalmanagementsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MICHAEL
 */
public class OtherServiceproviders extends javax.swing.JFrame {
     private JFrame frame;
      Connection con =null;
      PreparedStatement pst = null;
       ResultSet rs = null;
    public OtherServiceproviders() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namtxt = new javax.swing.JTextField();
        Registerbtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        viewbtn = new javax.swing.JButton();
        ctxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        atxt = new javax.swing.JTextArea();
        offset = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "OTHER SERVICE PROVIDERS REGISTRATION FORM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Elephant", 0, 24), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Company Name:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 182, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Company Contact:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 159, 174, 37));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Address:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 290, -1, -1));

        namtxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(namtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 95, 287, -1));

        Registerbtn.setBackground(new java.awt.Color(204, 204, 255));
        Registerbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Registerbtn.setForeground(new java.awt.Color(0, 51, 51));
        Registerbtn.setText("Register");
        Registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        resetbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        resetbtn.setForeground(new java.awt.Color(51, 51, 255));
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        backbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(153, 0, 255));
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, -1));

        exitbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(153, 153, 0));
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Services Offered:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, -1, -1));

        viewbtn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewbtn.setForeground(new java.awt.Color(153, 0, 0));
        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        ctxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(ctxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 162, 287, -1));

        atxt.setColumns(20);
        atxt.setRows(5);
        jScrollPane1.setViewportView(atxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 290, 90));

        offset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(offset, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
         //You must declare the Jframe on the top
        frame = new JFrame();
         if (JOptionPane.showConfirmDialog(frame, "Cofirm if you want to exit", "Other Service Providers Form",
             JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
             System.exit(0);
         }
    }//GEN-LAST:event_exitbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
            this.dispose();    
            Admin_Dashboard ad = new Admin_Dashboard();
            ad.setVisible(true);
                   
    }//GEN-LAST:event_backbtnActionPerformed

    private void RegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterbtnActionPerformed
        try{
      
        String sql = " INSERT INTO service_providers (company_name, contacts, service_type, address ) VALUES (?,?,?,?)";
        con = DriverManager.getConnection("jdbc:mysql://localhost/rentalmanagementsystem","root","");
        pst = con.prepareStatement(sql);
        pst.setString(1,namtxt .getText());
        pst.setString(2, ctxt.getText());
        pst.setString(3,  offset.getText());
        pst.setString(4, atxt.getText());
        
           
         if(namtxt.getText().equals("") || ctxt.getText().equals("") || offset.getText().equals("") || atxt.getText().equals("") ){
             JOptionPane.showMessageDialog(null,"Some fields not filled in..!!\n Please Fill them to continue.","Warning",JOptionPane.WARNING_MESSAGE);
         }
         
         else
         {
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registration of Other Service Providers is Successful");
             namtxt.setText(" ");
             ctxt.setText(" ");
             offset.setText("");
             atxt.setText("");
                   }
             this.dispose();
        } 
        
        catch(HeadlessException | SQLException ex){
        JOptionPane.showMessageDialog(null,ex);
        }
      
    }//GEN-LAST:event_RegisterbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
          namtxt.setText(" ");
          ctxt.setText(" ");
          offset.setText(" ");
          atxt.setText("");
           
           
    }//GEN-LAST:event_resetbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
       this.dispose();
     //  View_Leaders leader = new View_Leaders();
      // leader.setVisible(true);
    }//GEN-LAST:event_viewbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtherServiceproviders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtherServiceproviders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtherServiceproviders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtherServiceproviders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtherServiceproviders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registerbtn;
    private javax.swing.JTextArea atxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JTextField ctxt;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField namtxt;
    private javax.swing.JTextField offset;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
