/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package houserentalmanagementsystem;

/**
 *
 * @author MICHAEL
 */
public class Tenant_Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form TreasurerDashboard
     */
    public Tenant_Dashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.           * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        rulesbtn = new javax.swing.JButton();
        serviceprovbtn = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        paymentbtn = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        viewroombtn = new javax.swing.JButton();
        sendcomplainbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        hlpbtn = new javax.swing.JButton();
        logbtn = new javax.swing.JButton();
        empbtn = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel2.setText("WELCOME TO TENANT DASHBOARD");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 13, -1, -1));

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("CLICK ACTIVITY YOU WANT TO PERFORM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 50, -1, -1));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(204, 102, 0));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText(">");
        jTextField11.setBorder(null);
        jTextField11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 612, -1, 40));

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(255, 255, 255));
        jTextField13.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(204, 102, 0));
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText(">");
        jTextField13.setBorder(null);
        jTextField13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 18, 30));

        rulesbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        rulesbtn.setText("view rules and regulations");
        rulesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesbtnActionPerformed(evt);
            }
        });
        jPanel1.add(rulesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 370, 30));

        serviceprovbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        serviceprovbtn.setForeground(new java.awt.Color(102, 102, 0));
        serviceprovbtn.setText("view LOCAL service providers");
        serviceprovbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serviceprovbtnActionPerformed(evt);
            }
        });
        jPanel1.add(serviceprovbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(204, 102, 0));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText(">");
        jTextField12.setBorder(null);
        jTextField12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 149, -1, 30));

        paymentbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        paymentbtn.setForeground(new java.awt.Color(0, 0, 255));
        paymentbtn.setText("view rent Payment details");
        paymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentbtnActionPerformed(evt);
            }
        });
        jPanel1.add(paymentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 340, -1));

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(255, 255, 255));
        jTextField14.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(204, 102, 0));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText(">");
        jTextField14.setBorder(null);
        jTextField14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 101, -1, 30));

        jTextField24.setEditable(false);
        jTextField24.setBackground(new java.awt.Color(255, 255, 255));
        jTextField24.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField24.setForeground(new java.awt.Color(204, 102, 0));
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText(">");
        jTextField24.setBorder(null);
        jTextField24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 20, 30));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(204, 102, 0));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText(">");
        jTextField9.setBorder(null);
        jTextField9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 192, 20, 30));

        viewroombtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        viewroombtn.setForeground(new java.awt.Color(153, 0, 153));
        viewroombtn.setText("view rooms");
        viewroombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewroombtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewroombtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, -1));

        sendcomplainbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        sendcomplainbtn.setForeground(new java.awt.Color(51, 0, 255));
        sendcomplainbtn.setText("send complains");
        sendcomplainbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendcomplainbtnActionPerformed(evt);
            }
        });
        jPanel1.add(sendcomplainbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 153));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 800, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 51));
        jButton6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 0, 51));
        jButton6.setText("LOG OUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 800, -1, -1));

        jButton7.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 102, 255));
        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 736, -1, -1));

        jButton8.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 102, 102));
        jButton8.setText("LOGOUT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 736, -1, -1));

        jButton16.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 51, 0));
        jButton16.setText("View Report");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 650, 223, 40));

        hlpbtn.setBackground(new java.awt.Color(255, 153, 153));
        hlpbtn.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        hlpbtn.setForeground(new java.awt.Color(51, 51, 255));
        hlpbtn.setText("HELP");
        hlpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlpbtnActionPerformed(evt);
            }
        });
        jPanel1.add(hlpbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        logbtn.setBackground(new java.awt.Color(255, 153, 153));
        logbtn.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        logbtn.setForeground(new java.awt.Color(0, 255, 102));
        logbtn.setText("LOGOUT");
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, -1, -1));

        empbtn.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        empbtn.setForeground(new java.awt.Color(0, 204, 204));
        empbtn.setText("view employees");
        empbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empbtnActionPerformed(evt);
            }
        });
        jPanel1.add(empbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 278, 30));

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(255, 255, 255));
        jTextField15.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(204, 102, 0));
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText(">");
        jTextField15.setBorder(null);
        jTextField15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 18, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentbtnActionPerformed
    //    RecordProjects rp = new RecordProjects();
    //    rp.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_paymentbtnActionPerformed
 
    private void rulesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesbtnActionPerformed
         this.dispose();
     //   View_Report vr = new View_Report();
      //   vr.setVisible(true);         
    }//GEN-LAST:event_rulesbtnActionPerformed

    private void viewroombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewroombtnActionPerformed
      this.dispose();
     ViewRooms vr = new ViewRooms();
     vr.setVisible(true);
     
    }//GEN-LAST:event_viewroombtnActionPerformed

    private void sendcomplainbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendcomplainbtnActionPerformed
        this.dispose();
      //  Record_Expenses re = new Record_Expenses();
     //   re.setVisible(true);
    }//GEN-LAST:event_sendcomplainbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              this.dispose();
         Login log = new Login();
         log.setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
          this.dispose();
        Logout lg = new Logout();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void serviceprovbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceprovbtnActionPerformed
        this.dispose();
        ViewServiceProviders vs = new ViewServiceProviders();
        vs.setVisible(true);
    }//GEN-LAST:event_serviceprovbtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           this.dispose();
        Login log = new Login();
        log.setVisible(true);   
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
         this.dispose();
        Logout lg = new Logout();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void hlpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlpbtnActionPerformed
             this.dispose();
         Login log = new Login();
         log.setVisible(true); 
    }//GEN-LAST:event_hlpbtnActionPerformed

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed
         this.dispose();
        Logout lg = new Logout();
        lg.setVisible(true);
    }//GEN-LAST:event_logbtnActionPerformed

    private void empbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empbtnActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_empbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tenant_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tenant_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tenant_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tenant_Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tenant_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton empbtn;
    private javax.swing.JButton hlpbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton logbtn;
    private javax.swing.JButton paymentbtn;
    private javax.swing.JButton rulesbtn;
    private javax.swing.JButton sendcomplainbtn;
    private javax.swing.JButton serviceprovbtn;
    private javax.swing.JButton viewroombtn;
    // End of variables declaration//GEN-END:variables
}
